### ISSUE TITLE
Support RTX 50xx - Series

### ISSUE THREAD

**Issue by NikoGrano** [ahmetoner/whisper-asr-webservice#312]
Updating PyTorch will solve this issue:

```diff

diff --git a/Dockerfile.gpu b/Dockerfile.gpu
index 903b7b3..468e0e6 100644
--- a/Dockerfile.gpu
+++ b/Dockerfile.gpu
@@ 
-RUN $POETRY_VENV/bin/pip install torch==2.6.0+cu126 torchaudio==2.6.0+cu126 --index-url https://download.pytorch.org/whl/cu126
+RUN $POETRY_VENV/bin/pip install torch==2.7.1+cu128 torchaudio==2.7.1+cu128 --index-url https://download.pytorch.org/whl/cu128

 EXPOSE 9000

diff --git a/pyproject.toml b/pyproject.toml
index 7682913..131dcbf 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -30,14 +30,14 @@ tqdm = "^4.67.1"
 llvmlite = "^0.44.0"
 numba = "^0.61.0"
 torch = [
-    { version = "2.6.0", source = "pypi", markers = "sys_platform == 'darwin'"},
-    { version = "2.6.0", source = "pypi", markers = "platform_machine == 'aarch64' and sys_platform != 'darwin'"},
-    { version = "2.6.0", source = "pytorch-cpu", markers = "platform_machine == 'x86_64' and sys_platform != 'darwin'" },
+    { version = "2.7.1", source = "pypi", markers = "sys_platform == 'darwin'"},
+    { version = "2.7.1", source = "pypi", markers = "platform_machine == 'aarch64' and sys_platform != 'darwin'"},
+    { version = "2.7.1", source = "pytorch-cpu", markers = "platform_machine == 'x86_64' and sys_platform != 'darwin'" },
 ]
 torchaudio = [
-    { version = "2.6.0", source = "pypi", markers = "sys_platform == 'darwin'"},
-    { version = "2.6.0", source = "pypi", markers = "platform_machine == 'aarch64' and sys_platform != 'darwin'"},
-    { version = "2.6.0", source = "pytorch-cpu", markers = "platform_machine == 'x86_64' and sys_platform != 'darwin'" },
+    { version = "2.7.1", source = "pypi", markers = "sys_platform == 'darwin'"},
+    { version = "2.7.1", source = "pypi", markers = "platform_machine == 'aarch64' and sys_platform != 'darwin'"},
+    { version = "2.7.1", source = "pytorch-cpu", markers = "platform_machine == 'x86_64' and sys_platform != 'darwin'" },
 ]

 [poetry.group.dev.dependencies]

```

**Logs:**
```
INFO:speechbrain.utils.quirks:Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]
INFO:speechbrain.utils.quirks:Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
100%|█████████████████████████████████████| 2.88G/2.88G [05:54<00:00, 8.72MiB/s]s]
/app/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:235: UserWarning:
NVIDIA GeForce RTX 5090 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
Traceback (most recent call last):
  File "/app/.venv/bin/whisper-asr-webservice", line 3, in <module>
    from app.webservice import start
  File "/app/app/webservice.py", line 20, in <module>
    asr_model.load_model()
  File "/app/app/asr_models/openai_whisper_engine.py", line 19, in load_model
    self.model = whisper.load_model(name=CONFIG.MODEL_NAME, download_root=CONFIG.MODEL_PATH).cuda()
  File "/app/.venv/lib/python3.10/site-packages/whisper/__init__.py", line 155, in load_model
    model.load_state_dict(checkpoint["model_state_dict"])
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2581, in load_state_dict
    raise RuntimeError(
RuntimeError: Error(s) in loading state_dict for Whisper:
        While copying the parameter named "encoder.blocks.0.attn.query.weight", whose dimensions in the model are torch.Size([1280, 1280]) and whose dimensions in the checkpoint are torch.Size([1280, 1280]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
        While copying the parameter named "encoder.blocks.0.attn.key.weight", whose dimensions in the model are torch.Size([1280, 1280]) and whose dimensions in the checkpoint are torch.Size([1280, 1280]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
        While copying the parameter named "encoder.blocks.0.attn.value.weight", whose dimensions in the model are torch.Size([1280, 1280]) and whose dimensions in the checkpoint are torch.Size([1280, 1280]), an exception occurred : ('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n',).
```

**Comment by palik-l** [comment]
Thanks, this worked for me with my NVIDIA GeForce RTX 5060 Ti and CUDA Version 13.0!

I made the following changes to the pyproject.toml file:


```toml

[project.optional-dependencies]
cpu = [
"torch (==2.7.1)",
"torchaudio (==2.7.1)"
]
cuda = [
"torch (==2.7.1+cu128)",
"torchaudio (==2.7.1+cu128)"
]

```

and

```toml

[[tool.poetry.source]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu128"
priority = "explicit"

```

Then I rebuilt Docker and everything ran successfully.
