### ISSUE TITLE
need rtx5090 gpu card support

### ISSUE THREAD

**Issue by simplify123** [ahmetoner/whisper-asr-webservice#335]
```abc
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.5.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint .venv/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`
/app/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:287: UserWarning: 
NVIDIA GeForce RTX 5090 D with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 D GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
  warnings.warn(
No language specified, language will be first be detected for each audio file (increases inference time).
>>Performing voice activity detection using Pyannote...
Model was trained with pyannote.audio 0.0.1, yours is 3.3.2. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.7.1+cu126. Bad things might happen unless you revert torch to 1.x.
Traceback (most recent call last):
  File "/app/.venv/bin/whisper-asr-webservice", line 3, in <module>
    from app.webservice import start
  File "/app/app/webservice.py", line 20, in <module>
    asr_model.load_model()
  File "/app/app/asr_models/mbain_whisperx_engine.py", line 26, in load_model
    self.model['whisperx'] = whisperx.load_model(
  File "/app/.venv/lib/python3.10/site-packages/whisperx/__init__.py", line 21, in load_model
    return asr.load_model(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/whisperx/asr.py", line 404, in load_model
    vad_model = Pyannote(torch.device(device), use_auth_token=None, **default_vad_options)
  File "/app/.venv/lib/python3.10/site-packages/whisperx/vads/pyannote.py", line 237, in __init__
    self.vad_pipeline = load_vad_model(device, use_auth_token=use_auth_token, model_fp=model_fp)
  File "/app/.venv/lib/python3.10/site-packages/whisperx/vads/pyannote.py", line 45, in load_vad_model
    vad_pipeline = VoiceActivitySegmentation(segmentation=vad_model, device=torch.device(device))
  File "/app/.venv/lib/python3.10/site-packages/whisperx/vads/pyannote.py", line 196, in __init__
    super().__init__(segmentation=segmentation, fscore=fscore, use_auth_token=use_auth_token, **inference_kwargs)
  File "/app/.venv/lib/python3.10/site-packages/pyannote/audio/pipelines/voice_activity_detection.py", line 128, in __init__
    self._segmentation = Inference(model, **inference_kwargs)
  File "/app/.venv/lib/python3.10/site-packages/pyannote/audio/core/inference.py", line 114, in __init__
    self.model.to(self.device)
  File "/app/.venv/lib/python3.10/site-packages/lightning_fabric/utilities/device_dtype_mixin.py", line 55, in to
    return super().to(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1355, in to
    return self._apply(convert)
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 290, in _apply
    self._init_flat_weights()
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 215, in _init_flat_weights
    self.flatten_parameters()
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 271, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.5.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint .venv/lib/python3.10/site-packages/whisperx/assets/pytorch_model.bin`
/app/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:287: UserWarning: 
NVIDIA GeForce RTX 5090 D with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 D GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
  warnings.warn(
No language specified, language will be first be detected for each audio file (increases inference time).
>>Performing voice activity detection using Pyannote...
Model was trained with pyannote.audio 0.0.1, yours is 3.3.2. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.7.1+cu126. Bad things might happen unless you revert torch to 1.x.
Traceback (most recent call last):
  File "/app/.venv/bin/whisper-asr-webservice", line 3, in <module>
    from app.webservice import start
  File "/app/app/webservice.py", line 20, in <module>
    asr_model.load_model()
  File "/app/app/asr_models/mbain_whisperx_engine.py", line 26, in load_model
    self.model['whisperx'] = whisperx.load_model(
  File "/app/.venv/lib/python3.10/site-packages/whisperx/__init__.py", line 21, in load_model
    return asr.load_model(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/whisperx/asr.py", line 404, in load_model
    vad_model = Pyannote(torch.device(device), use_auth_token=None, **default_vad_options)
  File "/app/.venv/lib/python3.10/site-packages/whisperx/vads/pyannote.py", line 237, in __init__
    self.vad_pipeline = load_vad_model(device, use_auth_token=use_auth_token, model_fp=model_fp)
  File "/app/.venv/lib/python3.10/site-packages/whisperx/vads/pyannote.py", line 45, in load_vad_model
    vad_pipeline = VoiceActivitySegmentation(segmentation=vad_model, device=torch.device(device))
  File "/app/.venv/lib/python3.10/site-packages/whisperx/vads/pyannote.py", line 196, in __init__
    super().__init__(segmentation=segmentation, fscore=fscore, use_auth_token=use_auth_token, **inference_kwargs)
  File "/app/.venv/lib/python3.10/site-packages/pyannote/audio/pipelines/voice_activity_detection.py", line 128, in __init__
    self._segmentation = Inference(model, **inference_kwargs)
  File "/app/.venv/lib/python3.10/site-packages/pyannote/audio/core/inference.py", line 114, in __init__
    self.model.to(self.device)
  File "/app/.venv/lib/python3.10/site-packages/lightning_fabric/utilities/device_dtype_mixin.py", line 55, in to
    return super().to(*args, **kwargs)
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1355, in to
    return self._apply(convert)
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 915, in _apply
    module._apply(fn)
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 290, in _apply
    self._init_flat_weights()
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 215, in _init_flat_weights
    self.flatten_parameters()
  File "/app/.venv/lib/python3.10/site-packages/torch/nn/modules/rnn.py", line 271, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

solution:

```abc
pip install torch-2.7.0+cu128-cp310-cp310-manylinux_2_28_x86_64.whl

pip install torchaudio-2.7.0+cu128-cp310-cp310-manylinux_2_28_x86_64.whl

pip install torchvision-0.22.0+cu128-cp310-cp310-manylinux_2_28_x86_64.whl
```

**Comment by tarreislam** [comment]
This only solves part of the problem - it also needs to be rebuilt using newest cuda for best results. I think @ahmetoner is busy for a while, hopefully he will resolve this soon

**Comment by simplify123** [comment]
> This only solves part of the problem - it also needs to be rebuilt using newest cuda for best results. I think [@ahmetoner](https://github.com/ahmetoner) is busy for a while, hopefully he will resolve this soon

I already solve this,i rebuild using source code. you can have a test:

docker pull crpi-n9jif4z5nex2rnkd.cn-hangzhou.personal.cr.aliyuncs.com/docker_2025-images/whisper-asr-webservice_for_5090:latest

**Comment by juane1000** [comment]
Just hit this issue myself. New pc build.

**Comment by wallygit** [comment]
Hello,
I am running a 5060Ti and cuda 12.9 is installed on the host.
The 'docker run command for GPU generates the following error:

100%|███████████████████████████████████████| 139M/139M [00:28<00:00, 5.02MiB/s]

/app/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py:287: UserWarning:
NVIDIA GeForce RTX 5060 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5060 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
...

It would be great if someone could show me how to solve this problem.
regards Linus

btw.: the image provided by simplify123 above works for me on 5960Ti.
Would be great for learning how this image was made.

**Comment by NikoGrano** [comment]
Duplicate of #312

I would **highly recommend to not use some random image from random registry**. The image has not been checked by anyone nor it's source is public and might contain a **SECURITY** related risks!

There was attempt by author of this issue to post a PR replacing README.md file contents fully with redirect link to his registry. This is really **suspicious** and therefore would recommend to think at least twice before using that image.

Issue #312 contains updated diff to fix the support for 5000 -series and you can build it locally knowing there is not random code or injections made into the image and therefore it is as secure as this repository is.
